import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ignews2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}> testando </div>
      </div>
  )
}

export default Home
