import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Ignews2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.title}>
        testando
        <h1> 123</h1>
        <span className={styles.t1}> 123</span>
      </div>
      </div>
  )
}

export default Home
